#!/bin/bash

if [ "${RUNCICD_PATH}" == ""]; then 
  CTRLDIR=~/run-cicd
else  
  CTRLDIR=${RUNCICD_PATH}
fi

echo ""
echo "************* RUN BUILD&PUSH Container image *****************"
echo ""
echo "STEP1: Get Parameters"

# get parameters
if ([ $# -lt 4 ]) || ([ $# -eq 1 ] && [ "$1" == "-h" -o "$1" == "--help" ]); then
  echo "build-image <reg username> <reg password> <root directory> <dev lang>"
  echo " reg username: container image registry username "
  echo " reg password: container image registry password "
  echo " root directory: project의 최상위 디렉토리. '.'은 현재 디렉토리 의미함. "
  echo " dev lang: 개발 언어 (java, react, nodejs)"
  echo " config server: config server ingress name "
  echo " ex) ./build-image user1 password1 ~/work java"
  echo " ex) ./build-image user1 password1 . react"
  exit 1
fi

username=$1
password=$2
basedir=$3
devlang=$4
echo ""

# if the lang is java, do maven build. 
if [ "${devlang}" == "java" ]; then
  echo "*** RUN -> mvn clean package -DskipTests -f ${basedir}"
  mvn clean package -DskipTests -f ${basedir}  
fi

# if the lang is react, do copy config file if not exists.  
if ([ "${devlang}" == "react" ]) && ! ([ -f ${basedir}/default.conf.template  ]) ; then
  cp ${CTRLDIR}/dockerfile/default.conf.template ${basedir} 
fi

# set variables from config.properties: converted from '.' to '_'
echo "STEP2. Set environment variables "
if [ -f ${basedir}/cicd/cicd-common.properties ]; then  # NOT use config server 
  eval $(${CTRLDIR}/cmd/set-env ${basedir}/cicd/cicd-common.properties)
else
  eval $(${CTRLDIR}/cmd/set-env ${basedir}/deploy/cicd.properties)
fi

echo ""

# generte Dockerfile
echo "STEP3. Generate Dockerfile "

dockerfile_name=""

if [ "${devlang}" == "java" ]; then
  dockerfile_name=Dockerfile4java
elif [ "${devlang}" == "nodejs" ]; then
  dockerfile_name=Dockerfile4nodejs
elif [ "${devlang}" == "react" ]; then
  dockerfile_name=Dockerfile4react
else
  echo "NOT Supported Language!"
  exit 1
fi

# build image
echo "STEP4. Build image "
echo "image: ${image_registry}/${image_project}/${image_repository}:${image_tag}"
if [ "${devlang}" == "java" ]; then
  echo "*** RUN -> docker build --build-arg ARTIFACTORY_FILE=${image_repository}.jar -f ${CTRLDIR}/dockerfile/${dockerfile_name} -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}"
  docker build --build-arg ARTIFACTORY_FILE=${image_repository}.jar -f ${CTRLDIR}/dockerfile/${dockerfile_name} -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}
elif [ "${devlang}" == "nodejs" ]; then
  main_app=`${CTRLDIR}/cmd/jq '.main' ${basedir}/package.json`
  main_app="${main_app%\"}"
  main_app="${main_app#\"}"
  if [ "${main_app}" == "" ]; then
    echo "CAN'T get main application. It must be specified in package.json as 'main' key."
    exit 1
  fi

  echo "*** RUN -> docker build --build-arg MAIN_APP=${main_app} -f ${CTRLDIR}/dockerfile/${dockerfile_name} -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}"
  docker build --build-arg MAIN_APP=${main_app} -f ${CTRLDIR}/dockerfile/${dockerfile_name} -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}
else
  echo "*** RUN -> docker build -f ${CTRLDIR}/dockerfile/${dockerfile_name} -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}"
  docker build -f ${CTRLDIR}/dockerfile/${dockerfile_name} -t ${image_registry}/${image_project}/${image_repository}:${image_tag} ${basedir}
fi
echo ""
if [ $? -eq 1 ]; then
  echo "FAIL TO Build image "
  exit 1
fi

# login image registry to push image: parameters are provided from bamboo pipeline.
echo "STEP5. Login & Push image "
docker login ${image_registry} -u  ${username} -p ${password}
if [ $? == 1 ]; then
  echo "****** FAIL to login image registry: username is $1"
  exit 1
fi

# clone image as 'latest'
echo "*** RUN -> docker tag ${image_registry}/${image_project}/${image_repository}:${image_tag} ${image_registry}/${image_project}/${image_repository}:latest"
docker tag ${image_registry}/${image_project}/${image_repository}:${image_tag} ${image_registry}/${image_project}/${image_repository}:latest

# push them
echo "*** RUN -> docker push ${image_registry}/${image_project}/${image_repository}:${image_tag}"
docker push ${image_registry}/${image_project}/${image_repository}:${image_tag}
echo "*** RUN -> docker push ${image_registry}/${image_project}/${image_repository}:latest"
docker push ${image_registry}/${image_project}/${image_repository}:latest

echo ""
echo "************* END BUILD&PUSH Container image *****************"
echo ""
exit 0

