#!/bin/bash
#VERSION:1.0
echo ""
echo "************** CLEAR All resources *****************"
echo ""

# get parameters
if ([ $# -lt 1 ]) || ([ $# -eq 1 ] && [ "$1" == "-h" -o "$1" == "--help" ]); then
  echo "clear-all <application name>"
  echo " application name: image repository name을 지정하면 됨"
  echo " ex) ./clear-all webhook"
  exit 2
fi

app=$1

resource_kind=""
resource_postfix=""

function clearCMSecret() {
    nm=${app}-${resource_postfix}
    echo "try to delete=>${nm}"
    kubectl get ${resource_kind} ${nm} 2> /dev/null
    if [ $? -eq 0 ]; then
          kubectl delete ${resource_kind} ${nm}
    fi
}


# delete statefulset/deployments, service, ingress
kubectl delete statefulset ${app} 2> /dev/null
kubectl delete deploy ${app} 2> /dev/null
kubectl delete service ${app} 2> /dev/null 
kubectl delete ing ${app} 2> /dev/null 

# delete configmap
resource_kind=configmap
resource_postfix=cm
clearCMSecret

# delete secret
resource_kind=secret
resource_postfix=secret
clearCMSecret

echo ""
echo "************* All resources CLEARED *****************"
echo ""
exit 0

